export class PMR {

    constructor (
        public jist_id: number,
        public subject: string,
        public narr: string,
        public mission_name: string,
        public mission_remarks: string,
        public servicing_rssc: string,
        public sponsoring_cc_s_a: string,
        public sponsoring_component_or_organization: string,
        public requesting_unit_or_organization: string,
        public requested_constellation: string,
        public requested_flight: string,
        public aggregate_mission_time: string,
        public start_time: number,
        public end_time: number,
        public submitter_name: string,
        public submitter_organization: string,
        public submitter_phone_number: string,
        public submitter_niprnet_email: string,
        public submitter_siprnet_email: string,
        public requestor_name: string,
        public requestor_phone_number: string,
        public requestor_niprnet_email: string,
        public requestor_siprnet_email: string,
        public requestor_organization: string,
        public cjcsi_6250_01_mission_priority: string,
        public sdb_number_waiver: string,
        public cng_name: string, 
        public cng_owning_organization: string,
        public cvid_or_cvid_map: string,
        public cng_description: string,
        public port_mode: string,
        public data_rate: string,
        public pppoe_min_rate_kbps: number,
        public pppoe_max_rate_kbps: number,
        public direction: string,
        public reachback_method: string,
        public reachback_location: string,
        public broadcast_ccr: number,
        public broadcast_cir: number,
        public receive_only_terminal_configuration_files_update_periodicity: string,
        public network_specific_remarks: string,
        public is_strategic_service_requested: string,
        public all_terminals_in_same_channel_group: string,
        public terminal_id: string,
        public terminal_type: string,
        public terminal_name: string,
        public nomenclature: string,
        public antenna_polarization_capabilities: string,
        public antenna_size: string,
        public modem_type: string,
        public ecu_serial_number: number,
        public affiliated: string,
        public requested_band: string,
        public requested_fl_data_rate: number,
        public requested_rl_data_rate: number,
        public terminal_latitude: number,
        public terminal_longitude: number,
        public terminal_altitude: number,
        public cng_weight: number,
        public dscp_map: string,
        public method_of_postive_control: string,
        public name: string,
        public phone_number: string,
        public siprnet_email: string,
        public niprnet_email: string,
        public organization: string
    ){

    }
}
